// <auto-generated />
namespace Garage_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NullableType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NullableType));
        
        string IMigrationMetadata.Id
        {
            get { return "201806010757198_NullableType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
